
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - buildruns.shipwright.io
  - builds.shipwright.io
  - buildstrategies.shipwright.io
  - clusterbuildstrategies.shipwright.io
  resources:
  - customresourcedefinitions
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - operator.shipwright.io
  resources:
  - shipwrightbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.shipwright.io
  resources:
  - shipwrightbuilds/finalizers
  verbs:
  - update
- apiGroups:
  - operator.shipwright.io
  resources:
  - shipwrightbuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - shipwright-build-controller
  resources:
  - clusterrolebindings
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - shipwright-build-controller
  resources:
  - clusterroles
  verbs:
  - delete
  - patch
  - update
