apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: build-controller-namespace
rules:
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['get', 'create', 'update']
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create']