apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tektonconfig-operator-role
rules:
  - apiGroups:
      - operator.tekton.dev
    resources:
      - tektonconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
