# The following manifests contain a self-signed issuer CR and a certificate CR.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: shipwright-build
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shipwright-build-webhook-cert
  namespace: shipwright-build
spec:
  dnsNames:
  - shipwright-build-webhook.shipwright-build.svc
  - shipwright-build-webhook.shipwright-build.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: shipwright-build-webhook-cert
